# =======================================================
# Struktura Menu (Aktualizacja z zakładką oświetlenia)
# =======================================================

# Dodaliśmy LIGHT_CURVE do suwaków
sliders = GAMMA GLOBAL_SPEED HEIGHT_HIGH HEIGHT_MID HEIGHT_LOW BLOCK_SIZE_HIGH BLOCK_SIZE_MID BLOCK_SIZE_LOW WEATHER_VIGNETTE WEATHER_DESATURATION FOG_DENSITY_RAIN FOG_DENSITY_THUNDER LIGHT_CURVE

# Dodano nową zakładkę [LIGHTING]
screen = [POST_PROCESSING] [LIGHTING] [FLUIDS] [SKY_AND_CLOUDS] [WEATHER] *
screen.columns = 2

# --- ZAWARTOŚĆ ZAKŁADEK ---

screen.POST_PROCESSING = TONEMAP_MODE COLOR_PROFILE GAMMA
screen.POST_PROCESSING.columns = 1

# Dodajemy przyciski od oświetlenia
screen.LIGHTING = ENABLE_CUSTOM_BLOCK_LIGHT LIGHT_CURVE
screen.LIGHTING.columns = 1

screen.FLUIDS = WATER_STYLE LAVA_STYLE
screen.FLUIDS.columns = 1

screen.SKY_AND_CLOUDS = GLOBAL_SPEED <empty> <empty> ENABLE_HIGH_CLOUDS HEIGHT_HIGH BLOCK_SIZE_HIGH ENABLE_MID_CLOUDS HEIGHT_MID BLOCK_SIZE_MID ENABLE_LOW_CLOUDS HEIGHT_LOW BLOCK_SIZE_LOW
screen.SKY_AND_CLOUDS.columns = 3

screen.WEATHER = ENABLE_LOD_SUPPORT WEATHER_VIGNETTE WEATHER_DESATURATION FOG_DENSITY_RAIN FOG_DENSITY_THUNDER
screen.WEATHER.columns = 1